version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: ./.docker/dev/dockerfile
    stdin_open: true
    tty: true
    volumes: 
      - .:/code:delegated
  
  infrastructure:
    build:
      context: .
      dockerfile: ./.docker/infrastructure/dockerfile
    volumes:
      - "${HOME}/.aws:/root/.aws"

  deploy:
    build:
      context: .
      dockerfile: ./.docker/deploy/dockerfile
    volumes:
      - "${HOME}/.aws:/root/.aws"
