FROM docker.pkg.github.com/rileymathews/docker-kotlin-jvm/kotlin-jvm:3
WORKDIR /code
COPY . .
RUN gradle shadowjar

CMD [ "aws", "lambda", "update-function-code", "--function-name", "arn:aws:lambda:us-east-1:560435390111:function:rhythm-ninja-capo-optimizer-lambda-kotlin", "--zip-file", "fileb:///code/build/libs/code-all.jar" ]
