FROM rileymathews/kotlin:latest
WORKDIR /code
COPY . .
RUN gradle shadowjar

CMD [ "aws", "lambda", "update-function-code", "--function-name", "arn:aws:lambda:us-east-1:560435390111:function:rhythm-ninja-capo-optimizer-lambda-kotlin", "--zip-file", "fileb:///code/build/libs/code-all.jar" ]
