FROM rileymathews/base:latest
WORKDIR /code
COPY .infrastructure/template.yaml ./infrastructure.yaml
CMD [ "aws", "cloudformation", "update-stack", "--stack-name", "rhythm-ninja-capo-optimizer-lambda", "--template-body", "file:///code/infrastructure.yaml", "--capabilities", "CAPABILITY_IAM", "--capabilities", "CAPABILITY_NAMED_IAM", "--region", "us-east-1" ]
